### ISSUE TITLE
Swap ordering of label alignment buttons for down and left pointing arrows

### ISSUE THREAD

**Issue by DimaSamoz** [varkor/quiver#29] opened 2020-05-13 17:49 UTC
If an arrow is pointing down, the button to put the label to the _left_ of the arrow is on the right, and the button to put the label on the _right_ of the arrow is to the left (the tooltips for the buttons also seem to be mixed up, but they say the same thing for all directions). Would be great to have these swapped around so the directions are more intuitive! Similar inconsistency (though not as confusing) for left-pointing arrows, where the leftmost label alignment button is for bottom alignment and vice versa (it's the other way around for left-pointing arrows).

![image](https://user-images.githubusercontent.com/16826557/81845773-f17e6d80-9548-11ea-9009-b613f0883899.png)

**Comment by varkor** [comment] 2020-05-13 18:03
The directions (e.g. "Left align") are relative to the angle the arrow is pointing in. I feel this is the least confusing option, because otherwise the label alignment would appear to change when you reorient the arrow. I feel similarly about the buttons, which would appear to move when you reposition an arrow even when the label alignment remains constant.

I do agree that this is not ideal, though. Perhaps part of the issue is that the buttons are always horizontal. It could be nicer to position them both horizontally and vertically, so that they're always in the correct position. I'll play around with some ideas for this.

**Comment by varkor** [comment] 2020-11-18 15:38
In https://github.com/varkor/quiver/pull/39, there are now keyboard shortcuts for swapping the side of arrow labels. Though the buttons do not get rearranged, as I feel this would be confusing, hopefully this will mean it's less necessary to actually use the buttons: pressing "E" is much quicker. I'm going to close this, but if you still feel this is a real issue, let me know.

**Closed as completed by varkor** 2020-11-18 15:38 UTC
Labels: ui-ux
