### ISSUE TITLE
`//` for line breaks works in quiver but not in tikzcd

### ISSUE THREAD

**Issue by AlexanderZeilmann** [varkor/quiver#136] opened 2022-01-25 11:12 UTC
[This diagram](https://q.uiver.app/?q=WzAsMixbMCwwLCJtdWx0aVxcXFxsaW5lIl0sWzIsMCwib3RoZXJcXFxcbm9kZSJdXQ==) contains a `//` in two nodes. In quiver the line break is rendered, but the LaTeX output
```latex
\[\begin{tikzcd}
	multi\\line && other\\node
\end{tikzcd}\]
```
renders as
![Bildschirmfoto 2022-01-25 um 12 09 19](https://user-images.githubusercontent.com/901391/150966156-2c49e5ba-33c1-4675-b3bc-6e5e8f256111.png)

Ideally quiver should convert this to a syntax that works with tikzcd.

**Comment by varkor** [comment] 2022-01-25 11:53
This should be fairly easy to fix, so long as there's a convenient way to render newlines in tikz-cd. If anyone knows how to do this, please let me know :)

**Comment by AlexanderZeilmann** [comment] 2022-01-25 12:08
Wrapping it in an array should work
```latex
\begin{array}{c}
multi \\ line
\end{array}
```
but I have not tested it extensively.

**Comment by balacij** [comment] 2022-03-16 16:05
I am using `\parbox{3cm}{\centering Something That Is Longer Than Expected}` to get multiline working, however, it doesn't render with the mathematical font. I get an error with a normal `\\`, I'm not quite sure why. `\newline` and `\linebreak` are ignored as inputs.

**Comment by varkor** [comment] 2023-01-09 18:28
On reflection, this is more difficult than I first thought, since one has to determine which occurrences of `\\` are actually newlines, which I believe requires parsing the LaTeX. KaTeX is doing this already, but I'm not sure whether it's possible to extract this information somehow.

However, one can add newlines to diagrams manually using `\shortstack`.

**Comment by varkor** [comment] 2023-01-09 20:16
I think the correct solution here would be to disable new lines in **quiver**. I'm not sure this is possible yet with KaTeX, so I've opened https://github.com/KaTeX/KaTeX/issues/3773.

**Comment by varkor** [comment] 2023-04-13 18:43
Fixed in https://github.com/varkor/quiver/commit/a239252650751968577a981af20ebbea490fe07c (by disabling newlines).

**Comment by varkor** [comment] 2023-05-18 20:41
Unfortunately, I had to revert the fix due to the issue reported here: https://github.com/varkor/quiver/issues/163#issuecomment-1546983693.

**Comment by user202729** [comment] 2024-05-01 08:47
There's a discussion of this issue at [diagrams - tikz-cd quiver code not working - TeX - LaTeX Stack Exchange](https://tex.stackexchange.com/questions/660452/tikz-cd-quiver-code-not-working?noredirect=1&lq=1) . I think the third answer there has an automatic solution that can be implemented in quiver.

**Comment by varkor** [comment] 2024-05-01 12:26
@user202729: thanks for the suggestion. I'll look into this issue and #225 this evening.

**Comment by varkor** [comment] 2024-05-01 14:59
This is fixed by https://github.com/varkor/quiver/commit/46269555e260cd3da1deb90ebf1a5cd1893fd81c. You can test it out using https://q.uiver.app/dev/.

Let me know if you encounter any issues with it. I will push a new version of **quiver** when I am happy it is working as intended.

**Closed as completed by varkor** 2024-05-01 14:59 UTC
Labels: bug, tikz-cd-output, blocked

**Comment by cchanavat** [comment] 2024-12-11 14:09
It seems that when you change the text color of a label the `\\begin{array}{c} \\end{array}` padding disappear. For instance, create an edge with text `a \\ b `, then change the color, the output becomes:
```latex
\begin{tikzcd}
	\textcolor{rgb,255:red,214;green,92;blue,92}{a \\ b}
\end{tikzcd}
```

I pinpoint the issue at [line 431](https://github.com/varkor/quiver/blob/f969fc6a488455dc01c94417e775b7353cdd292f/src/quiver.mjs#L431), since if there is a color, it seems that this fix `format_label` is not applied.

**Comment by varkor** [comment] 2024-12-27 08:02
@cchanavat: thanks for reporting! The issue has been fixed in https://github.com/varkor/quiver/commit/629da2fad08a2590d2e6e7bf233724af903219ae, and will be available in the next version of **quiver**.
