### ISSUE TITLE
Immovable vertex bug

### ISSUE THREAD

**Issue by TimOphelders** [varkor/quiver#53] opened 2020-11-28 07:23 UTC
Occasionally some vertices cannot be moved. Loading the sharable link allows them to move again.

Using Google Chrome 86.0.4240.198 (Official Build) (64-bit)

**Comment by varkor** [comment] 2020-11-28 13:29
Thanks! I suspect this is happening because some other error occurs (e.g. on `mousedown`) and then blocks the code responsible for moving vertices from executing. If this happens again, could you check the JavaScript console to see if there are any errors, and post a screenshot of the error trace?

Even better, if someone can find a way to reproduce this issue.

**Comment by varkor** [comment] 2020-11-28 19:20
This should be fixed in https://github.com/varkor/quiver/commit/6728eed6638d65c61450ac62170f79c4c5256b07, which will be available in **quiver** 1.0.1 and is now live on https://q.uiver.app/dev/. Let me know if you encounter it again after this.

**Closed as completed by varkor** 2020-11-28 19:20 UTC
Labels: bug, release-notes
